README.md
=> Add demos description

README.md
Add the Geosearch demo
Thank you so much for contributing to MeiliSearch!
=> Add Geosearch demo

README.md
- add the missing instant meilisearch code-sandbox
- add a precision about the integration team ownership
=> Add instant-meilisearch codebox

README.md
Fixes #12 
Thank you so much for contributing to MeiliSearch!
=> Fix link for React MeiliSearch Demo

src/finding-crates/README.md, src/finding-crates/docs/index.html, src/finding-pypi/README.md, src/finding-pypi/docs/index.html, src/finding-rubygems/README.md, src/finding-rubygems/docs/index.html, src/geo-javascript/README.md, src/geo-javascript/index.html
=> Update MeiliSearch naming to Meilisearch

src/MoMA/src/App.vue, src/geo-javascript/src/app.js, src/nobel-prizes/src/meilisearch-client.js
=> Update search API Keys

src/typo-tolerance/src/main.js
=> Update transforItems to avoid error when there are no results

src/typo-tolerance/index.html
=> Add info on typo tolerance settings

README.md
Fixes #35
⚠️ This is also a test for the Vercel integration (rights needed for the tenant-token demo when creating a PR)
=> Update Meilisearch wording in the README.md

process/demo_update_ process.md
Adds demo update process to the repo
=> demo update process

src/ecommerce/.eslintrc.json, src/ecommerce/components/home/SearchFilters.jsx, src/ecommerce/components/home/SearchResult.jsx, src/ecommerce/components/layout/Layout.jsx, src/ecommerce/components/layout/NavBar.jsx, src/ecommerce/components/slider/Slider.jsx, src/ecommerce/package.json, src/ecommerce/pages/_app.jsx, src/ecommerce/pages/index.jsx, src/ecommerce/pages/product/[id].jsx
=> fix build error

src/geo-javascript/package.json, src/geo-javascript/src/app.js, src/geo-javascript/yarn.lock
**Update Geo-javascript Demo to v0.28**
- This update does not introduce any code-related breaking changes.
- Bumped instant-meilisearch to 0.8.0
=> update geo-js to v0.28

src/MoMA/package-lock.json, src/MoMA/package.json, src/MoMA/src/App.vue
**Update MoMA Demo to v0.28**
- This update does not introduce any code-related breaking changes.
- Bumped meilisearch-js version to v0.27.0
- Bumped instant-meilisearch to 0.8.0
=> update moma-demo to v0.28

src/ecommerce/components/layout/Layout.jsx, src/ecommerce/package.json, src/ecommerce/yarn.lock
It fixes the ecommerce demo that is down due to the deletion of the old server in MS Cloud and ensures compatibility with the latest version.
=> update demo and point host to the new server

src/MoMA/public/index.html, src/ecommerce/package.json, src/ecommerce/pages/_app.jsx, src/ecommerce/yarn.lock, src/finding-crates/docs/index.html, src/finding-pypi/docs/index.html, src/geo-javascript/index.html, src/nobel-prizes/public/index.html, src/typo-tolerance/index.html
Fixes https://github.com/meilisearch/devrel/issues/398
=> Add fathom

src/ecommerce/pages/_app.jsx
=> Fix linter errors

README.md
Fixes #120 
- Adds the Where To Watch Demo to the list of available demos.
=> Add Where2Watch Demo

src/finding-pypi/docs/img/meili.svg, src/finding-pypi/docs/index.html
Fixes #61 
- Updates all the Meilisearch logo occurrences on the Pypi demo page
=> Update Meilisearch logo on Pypi demo

README.md
Fixes #132 
- Add ecommerce demo to README list
=> Added ecommerce demo to README list

src/matching-strategy/index.html
Fixes #130 
-Adds a clickable icon link with descriptive text ( a stand alone icon didnt seem intuitive enough) to read up more on matching strategy. 
=> feat: Add link for more details on Matching Strategy

src/MoMA/package-lock.json, src/MoMA/package.json, src/MoMA/src/App.vue
**Update MoMA demo to v0.29**
* Bumped meilisearch-js version to v0.28.0
* Bumped vue-instantsearch to 4.6.0
* API Key changed as creating a new MS cloud project generates a new master key.
* The host URL changed because the MS cloud server update requires creating a new project.
=> update MoMA demo to v0.29

src/geo-javascript/package.json, src/geo-javascript/src/app.js, src/geo-javascript/yarn.lock
**Update Geo-javascript demo to v0.29**
* Bumped meilisearch-js version to v0.28.0
* API Key changed as creating a new MS cloud project generates a new master key.
* The host URL changed because the MS cloud server update requires creating a new project.
=> update geo-javascript demo to v0.29

src/matching-strategy/package.json, src/matching-strategy/yarn.lock
**Migrate Matching strategy demo to MS cloud demos project**
* Bumped meilisearch-js version to v0.28.0
* API Key and host URL changed as a result of migration.
=> Migrate Matching strategy demo to MS cloud demos project

src/typo-tolerance/package-lock.json, src/typo-tolerance/package.json
**Update Typo-tolerance demo to v0.29**
* Migrated demo to MS cloud
* API Key and host URL changed as a result of migration.
=> update typo-tolerance demo to v0.29

src/nobel-prizes/package.json, src/nobel-prizes/src/meilisearch-client.js, src/nobel-prizes/yarn.lock
**Update Nobel prizes demo to v0.29**
* Bumped meilisearch-js version to v0.28.0
* Bumped vue-instantsearch to 4.6.0
* API Key changed as creating a new MS cloud project generates a new master key.
* The host URL changed because the MS cloud server update requires creating a new project.
=> update nobel-prizes demo to v0.29

src/geo-javascript/package.json, src/geo-javascript/yarn.lock
**Update Geo-javascript demo to v0.30**
- This update does not introduce any breaking changes.
=> update geo-js demo to v0.30

src/MoMA/package-lock.json, src/MoMA/package.json
**Update demo to v0.30**
- This update does not introduce any breaking changes.
- Bumped meilisearch-js version to v0.30.0
=> update moma demo to v0.30

src/typo-tolerance/package-lock.json, src/typo-tolerance/package.json
**Update demo to v0.30**
- This update does not introduce any code-related breaking changes.
=> update typo-tolerance demo to v0.30

src/numbered-pagination/README.md, src/numbered-pagination/package.json, src/numbered-pagination/yarn.lock
**Migrate the demo to the existing demo server**
- It does not introduce any code-related breaking changes.
- Update Readme title 
=> Migrate numbered pagination demo to existing demo server

src/matching-strategy/package.json, src/matching-strategy/yarn.lock
**Update demo to v0.30**
- This update does not introduce any breaking changes.
- Bumped meilisearch-js version to v0.30.0
=> update matching strategy demo to v0.30

src/federated-search/pages/index.js, src/federated-search/setup/index.js
Modify index names to avoid conflict with other indexes in meilisearch-demos instance
=> Modify index names to avoid conflict in meilisearch-demos instance

README.md
Fixes #185 
Fixes #150
Fixes #149 
- Adds demos to the list
=> Add demos to readme

README.md
- Add link to saas demo
- Update links to include UTMs
- General README updates
=> Add SaaS demo and UTM tracking

src/MoMA/public/index.html, src/federated-search/pages/_document.js, src/geo-javascript/index.html, src/matching-strategy/index.html, src/nobel-prizes/public/index.html, src/numbered-pagination/index.html, src/tenant-token/frontend/public/index.html, src/typo-tolerance/index.html
=> Add google analytics
